.TH ATOPCAT 1 "January 2024" "Linux"
.SH NAME
.B atopcat
- concatenate raw log files to stdout
.SH SYNOPSIS
.P
.B atopcat [-dv] rawfile [rawfile]...
.P
.SH DESCRIPTION
The program
.I atopcat
can be used to concatenate several raw log files into one stream (stdout).
In this way, raw log files can be merged into one larger file by redirecting
stdout to a file. Alternatively, merged data from several raw log files
can be transferred directly into
.I atop
or
.I atopsar
via a pipe.

Options:
.PP
.TP 5
.B -d
dry-run: read logfile(s) but do not generate output on stdout
.PP
.TP 5
.B -v
verbose: print one line per sample containing date/time, interval length
in seconds, compressed length of the system-level information,
compressed length of the process-level information,
compressed length of the cgroup-level information, and
compressed length of the PID list.
.SH EXAMPLES
Concatenate the raw log files of five contiguous working days,
write it into a new raw log file for that week and
view that week interactively:
.PP
.TP 12
.B \  atopcat /var/log/atop/atop_2024021[0-4] > week_2024_7
.TP 12
.B \  atop -r week_2024_7
.PP
Concatenate the raw log files of a week and view that week interactively
(since
.I atop
reads from a pipe, previous intervals can not be retrieved while viewing): 
.PP
.TP 12
.B \  atopcat /var/log/atop/atop_2024021[0-6] | atop -r -
.PP
Concatenate all raw log files of January 2024 and generate parsable
output about the CPU utilization:
.PP
.TP 12
.B \  atopcat /var/log/atop/atop_202401?? | atop -r -  -PCPU
.PP
Concatenate the daily raw log files of February 3 and 4,
and generate a report about memory utilization from 14:00h on the first day
till 11:00h on the second day:
.PP
.TP 12
.B \  atopcat /var/log/atop/atop_2024020[34] |
.B \  atopsar -m  -r -  -b 202402031400  -e 202402041100
.PP
Repair a raw log file from which the last interval has not been
completely written (e.g. if you intend to expand the file with new samples):
.PP
.TP 12
.B \  atopcat /var/log/atop/atop_20240303 > /tmp/repaired
.PP
In the latter case,
.B atopcat
reports that the input file is incomplete and stops after the last consistent
sample.
.SH SEE ALSO
.B atop(1),
.B atopsar(1),
.B atophide(1),
.B atopconvert(1)
.br
.B https://www.atoptool.nl
.SH AUTHOR
Gerlof Langeveld (gerlof.langeveld@atoptool.nl)
