#!/bin/bash

# Make a new version.c with the actual version and current date filled.
#
CURDATE=$(date +%Y\\/%m\\/%d\ %H:%M:%S)
CURVERS=$(git branch | grep '^\* ' | sed -e 's/[* ]//g')

if [ "$CURVERS" = master ]
then
	echo $(basename $0): MASTER VERSION CAN NOT BE DISTRIBUTED!!!! >&2
	exit 1
fi

cat version.SKEL                     |
	sed -e "s/CURVERS/$CURVERS/" |
	sed -e "s/CURDATE/$CURDATE/"  > version.c
