#!/bin/bash

# Make a new version.h with the actual version and current date filled.
#
CURDATE=$(date +%Y/%m/%d\ %H:%M:%S)
CURVERS=$(git branch | grep '^\* ' | sed -e 's/[* ]//g')

if [ "$CURVERS" = master ]
then
	echo $(basename $0): MASTER VERSION CAN NOT BE DISTRIBUTED!!!! >&2
	exit 1
fi

echo "#define	ATOPVERS	\"$CURVERS\""	 > version.h
echo "#define	ATOPDATE	\"$CURDATE\""	>> version.h
