name: Compilation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Config
      run: sudo apt install libncurses5-dev
    - name: make
      run: make
