struct icmpv4_stats_wrong {
	count_t InMsgs;
	count_t InErrors;
	count_t InDestUnreachs;
	count_t InTimeExcds;
	count_t InParmProbs;
	count_t InSrcQuenchs;
	count_t InRedirects;
	count_t InEchos;
	count_t InEchoReps;
	count_t InTimestamps;
	count_t InTimestampReps;
	count_t InAddrMasks;
	count_t InAddrMaskReps;
	count_t OutMsgs;
	count_t OutErrors;
	count_t OutDestUnreachs;
	count_t OutTimeExcds;
	count_t OutParmProbs;
	count_t OutSrcQuenchs;
	count_t OutRedirects;
	count_t OutEchos;
	count_t OutEchoReps;
	count_t OutTimestamps;
	count_t OutTimestampReps;
	count_t OutAddrMasks;
	count_t OutAddrMaskReps;
};
